# Generated by Django 3.1.2 on 2020-11-10 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('preferences', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preference',
            name='area',
        ),
        migrations.AddField(
            model_name='preference',
            name='area',
            field=models.ManyToManyField(related_name='preference', to='profiles.Area'),
        ),
    ]
