# Generated by Django 3.1.2 on 2020-11-13 06:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Body',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Religion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=10)),
                ('gender', models.IntegerField()),
                ('birth', models.DateField()),
                ('height', models.FloatField()),
                ('hobby1', models.CharField(max_length=50)),
                ('hobby2', models.CharField(max_length=50, null=True)),
                ('blood', models.CharField(max_length=50)),
                ('smoke', models.CharField(max_length=50)),
                ('drink', models.CharField(max_length=50)),
                ('intro', models.CharField(max_length=150)),
                ('age', models.IntegerField(default=0)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.area')),
                ('body', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.body')),
                ('education', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.education')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.job')),
                ('religion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.religion')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
