# Generated by Django 3.1.2 on 2020-11-10 03:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=10)),
                ('gender', models.IntegerField()),
                ('birth', models.DateField()),
                ('height', models.FloatField()),
                ('body', models.CharField(max_length=50)),
                ('hobby1', models.CharField(max_length=50)),
                ('hobby2', models.CharField(max_length=50)),
                ('blood', models.CharField(max_length=50)),
                ('religion', models.CharField(max_length=50)),
                ('smoke', models.CharField(max_length=50)),
                ('drink', models.CharField(max_length=50)),
                ('education', models.CharField(max_length=50)),
                ('job', models.CharField(max_length=50)),
                ('area', models.CharField(max_length=20)),
                ('intro', models.CharField(max_length=150)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
