# Generated by Django 3.1.2 on 2020-11-11 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20201111_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='body',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.body'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='education',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.education'),
        ),
    ]
