# Generated by Django 3.1.2 on 2020-11-09 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20201103_1616'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='hobby',
            new_name='hobby1',
        ),
        migrations.AddField(
            model_name='profile',
            name='area',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='hobby2',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='intro',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
